name: Telegram Forwarder Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          ls -la
          pip install -r requirements.txt

      - name: Run bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SOURCES: ${{ secrets.SOURCES }}
          DESTINATION: ${{ secrets.DESTINATION }}
          FOOTER: ${{ secrets.FOOTER }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          POSTS_PER_DAY: ${{ secrets.POSTS_PER_DAY }}
          START_LOCAL: ${{ secrets.START_LOCAL }}
          END_LOCAL: ${{ secrets.END_LOCAL }}
        run: python mirror_channel.py
